#!/bin/bash
[[ -f $HOME/.profile ]] && source $HOME/.profile
[[ -f $HOME/.zprofile ]] && source $HOME/.zprofile
INTERNALIP=$(cat /etc/resolv.conf | grep nameserver | awk '{print $2; exit;}')
DBUSPID=$(pidof dbus-launch)
sh -ic "if [ -z $DBUSPID ]; then export DISPLAY=$INTERNALIP:0.0; dbus-launch --exit-with-x11; fi;"
export DISPLAY=$INTERNALIP:0.0
$@